"""add_age_months_to_pet

Revision ID: fa87a3fb178f
Revises: a74b8f7f2ac9
Create Date: 2026-06-01 15:31:18.439319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa87a3fb178f'
down_revision = 'a74b8f7f2ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_months', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('age_months')

    # ### end Alembic commands ###
